name: build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: |
          python3 -m pip install poetry
          poetry install
      - name: Type checks
        run: poetry run mypy .
      - name: Run tests
        run: |
          poetry run coverage run --source=menta -m pytest && poetry run coverage report -m
      - name: Create report & badge
        run: |
          poetry run coverage html
          poetry run coverage-badge -o coverage.svg
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: |
            coverage.svg
            htmlcov/
          if-no-files-found: error
